

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CathLab
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class cathlabEntities1 : DbContext
{
    public cathlabEntities1()
        : base("name=cathlabEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Location> Locations { get; set; }

    public DbSet<Login> Logins { get; set; }

    public DbSet<Manufacturer> Manufacturers { get; set; }

    public DbSet<PartNumber> PartNumbers { get; set; }

    public DbSet<Product> Products { get; set; }

    public DbSet<ProductName> ProductNames { get; set; }

    public DbSet<ProductType> ProductTypes { get; set; }

    public DbSet<sysdiagram> sysdiagrams { get; set; }

}

}

