//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CathLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartNumber
    {
        public PartNumber()
        {
            this.Products = new HashSet<Product>();
        }
    
        public string PartNum { get; set; }
        public string NameSize { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> Cost { get; set; }
        public string MediClick { get; set; }
        public Nullable<int> Par { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
