
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CathLab
{

using System;
    using System.Collections.Generic;
    
public partial class ProductType
{

    public ProductType()
    {

        this.PartNumbers = new HashSet<PartNumber>();

    }


    public int ID { get; set; }

    public string Type { get; set; }



    public virtual ICollection<PartNumber> PartNumbers { get; set; }

}

}
